source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'socket.IO', '~> 0.4'

target 'ActiveStack_Example', :exclusive => true do
  pod "ActiveStack", :path => "../"
end

target 'ActiveStack_Tests', :exclusive => true do
  pod "ActiveStack", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
